### ISSUE TITLE
Sales order: just-in-time creation of conditions for a product without conditions

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3925]

**Comment by metas-lc** [comment]
IT
0. Configs: 
de.metas.order.NoPriceConditionsColorName = Rot
de.metas.order.TemporaryPriceConditionsColorName = Gelb

1. have some discount schema breaks (make sure some have the product you want, other some other products. Also, one with the product you want should have Break Value)
2. add them to some bpartners - customer and vendors. The bpartner you are going to use should not have any discount schema
3. create a new sales order for a bpartner, add a product
=> No price conditions indicator has a red dot OK
4. select the line, go to actions - Pricing Conditions
=> you have at least one line, editable, containing: readonly: BPartner, IsCustomer, Price system, editable: Price, Trade discount, Payment term (mandatory) OK
=> you have some lines, with the pricing conditions assigned to other bpartners, but only those that matches: product, Break Value, type break. Also, you can filter for isCustomer: yes, no, null. Then you can also see those from vendors OK 
=> (also tried it with discount schema flat and it was not shown in actions OK)
5. select a readonly line, choose action: Copy to editable
=> data from that line, is now in your editable line (besides bpartner and isCustomer) OK
=> you cannot edit Price after that, if pricesystem is set (if you use fixed price, is editable) OK
6. press on done
=> data is set in orderline accordingly OK
=> No price conditions indicator has a yellow dot OK
7. use pricing conditions again, but this time don't copy. Set the fields manually
=> i could set Price and Trade discount, but couldn't set Payment Term NOK
8. use pricing conditions again, copy another line
9. select your line, (save?)
=> i can't find the save button ?
10. complete an order with temporary price conditions
=> you can't NOK
```
Error: Error Processing Document document: Standardauftrag...
Server error
Error Processing Document document: Standardauftrag 0014 Document Action: CO Cause: The order can not be completed because pricing conditions are missing. Please modify. (AdempiereException)
```


Regression. 
1. try to complete an order with a line without price conditions
=> you can't:
```
Error: Error Processing Document document: Standardauftrag...
Server error
Error Processing Document document: Standardauftrag 0014 Document Action: CO Cause: The order can not be completed because pricing conditions are missing. Please modify. (AdempiereException)
```
OK

**Comment by teosarca** [comment]
> 9. select your line, (save?)
> => i can't find the save button ? NOK

Cannot reproduce it, but i've introduced some params to the quickActions endpoint in order to be able to fetch all actions, even those internally disabled. So we will be able to trace why the action is not available.

> 10. complete an order with temporary price conditions
> => you can't NOK

Cannot reproduce.

> 11. create a purchase order, add a line, select the line, go to actions
> => pricing conditions action s not there NOK

Cannot reproduce. Same as 9.

**Comment by teosarca** [comment]
btw, what i've also fixed is: when u open pricing conditions and you have the editable row by default it will be intialized with order line's Price, Discount and Payment Term.

**Comment by metas-lc** [comment]
IT2
1. i noticed that if you have some flat discount schema for bpartner X, it's considered you have no price conditions, BUT when you start Pricing Conditions action, you don't get the editable line NOK right?

2. when u open pricing conditions and you have the editable row by default it will be intialized with order line's Price, Discount and Payment Term. OK

3. still cannot see save action. Cannot complete temp pricing cond order and pricing conditions action missing in purchase order

see https://w101.metasfresh.com:8443/window/143/1000883
https://w101.metasfresh.com:8443/window/181/1000884

![image](https://user-images.githubusercontent.com/16001666/40047556-7ac0fb12-5838-11e8-9ae9-b3d92b17995e.png)

![image](https://user-images.githubusercontent.com/16001666/40047610-98e2a0dc-5838-11e8-8443-76957f05b6e6.png)

![image](https://user-images.githubusercontent.com/16001666/40047662-c1f2d99c-5838-11e8-9100-18fbb269a730.png)

**Comment by teosarca** [comment]
> 3. till cannot see save action. Cannot complete temp pricing cond order and pricing conditions action missing in purchase order NOK

Yup, because that BPartner does not have discount schema defined.
How can you find that out now (i know, not obvious):
* take a look at the quickActions endpoint. Right click on it and open it in a new tab:
![image](https://user-images.githubusercontent.com/1244701/40101547-6c945a58-58f0-11e8-89e7-b1e30a95435d.png)

* edit the link and append `&all=true`. You will get all actions. Those disabled will have `disabled: true` but you also get the reason.
![image](https://user-images.githubusercontent.com/1244701/40101605-a95625a2-58f0-11e8-835c-5a4f27af1223.png)


Talked with @metas-mk  and we agreed it's acceptable for now.
In future the admin/power user could have some `right click -> inspect` option somewhere, will get all the actions will see why those are not available.

**Comment by teosarca** [comment]
> 1. i noticed that if you have some flat discount schema for bpartner X, it's considered you have no price conditions, BUT when you start Pricing Conditions action, you don't get the editable line NOK right?

Fixed. The test case is to have a discount schema with some breaks defined but Discount Type shall be `Flat`.
e.g.
![image](https://user-images.githubusercontent.com/1244701/40113137-0ed187ee-5911-11e8-8809-717c75c51215.png)


Expectation: breaks shall be completely ignored.

**Comment by metas-lc** [comment]
IT
I. flat discount schema

1. have a flat discount schema. Add it to a bpartner
2. go to sales order and create a new one, add a product
=> no price conditions OK
3. go to actions, start Pricing Conditions 
=> you get the editable line OK
4. copy from an existing line to the editable one 
=> works OK
5. select the editable line
=> you can use save button. Is that OK?
(if you use save button you will get a new line in flat discount schema and your order will still have the red dot OK?)
.
II. Save action in Pricing Conditions 
1. have a bpartner that has a discount schema, but no lines matching your product
2. create a new sales order for that bpartner, add product
3. go to actions "Pricing conditions", copy or manually set the data in editable line, press save
=> no errors OK
=> in discount schema a new line was added, for your product, with the data you set OK
.
III. Pricing Conditions in purchase orders
1. started without a discount schema in bpartner for vendor, but it had one in customer
=> nok it't taking the one from customer. Also, the filter is set on customer, save button is there NOK

![image](https://user-images.githubusercontent.com/16001666/40172535-7e2c3ef6-59d7-11e8-8b60-c3d5137cf3b5.png)

.
IV. Complete orders with temp/existing pricing conditions with products on  HUs
1. sales order. Complete a sales order with temp condition, then one with condition. Both having HUs 
=> you can complete them OK
2. purchase order. Complete a purchase order with temp condition, then one with condition. Both having HUs 
=> you can't, but not because of the HUs, but probably because the stuff in  Pricing Conditions happens on sales side NOK

V. other
what i noticed while testing..donno if it's a problem or not. Happens when the bpartner doesn't have discount schema set
![image](https://user-images.githubusercontent.com/16001666/40173073-48a00892-59d9-11e8-9652-a7e8bc05d36a.png)

**Comment by teosarca** [comment]
> 5. select the editable line
> => you can use save button. Is that OK?
> (if you use save button you will get a new line in flat discount schema and your order will still have the 
> red dot OK?)

i.e. The case is: BPartner has a discount schema set but the discount type is Flat and NOT Breaks.
In that case it shall be handled like there is no discount schema => you shall not be allowed to save the break line!

**Comment by metas-lc** [comment]
moved to test since the remaining issue was the one with discount schema without break

**Comment by metas-lc** [comment]
IT

1. no colors config, create order with product + bpartner without discount schema
=> order was completed, no errors OK

2. de.metas.order.NoPriceConditionsColorName = Rot
de.metas.order.TemporaryPriceConditionsColorName = Gelb
repeated the first IT

Questions / Problems:
1. create order with a bartner with a  discount schema. Create an order, add a product that's not in that discount schema.
=> the line is set directly on temporary (Gelb in my case) OK?

2. create order with a bartner with NO discount schema. Create an order, add a product.
=> the line is set on no pricing conditions (Rot in my case)  OK
use pricing conditions, copy an existing one, press done
=> the line is STILL on no pricing conditions (Rot in my case)  NOK
=> if you open pricing conditions action again, there is Gelb..?

3. Copy to editable: make a simple discount schema for a product and use it to copy it in Pricing conditions
=> the type was set to pricing system instead of none. Wanted?
![image](https://user-images.githubusercontent.com/16001666/41092407-7645e5d6-6a51-11e8-92df-8d25e35c2d36.png)

4. if i have multiple discount schema lines, should i see all of them? I had 2: one simple, one with price override with price system, and i only saw the second one OK?

**Comment by teosarca** [comment]
closing because it's too old
